[Appearance]
style=Fusion
custom_palette=true
color_scheme_path=$HOME/.config/qt6ct/colors/mocha.conf
icon_theme=Papirus
standard_dialogs=xdgdesktopportal

[Interface]
menus_have_icons=true
activate_item_on_single_click=1
buttonbox_icons=1
icon_size=24
